//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplitByte {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplitByte.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Custom&gt;.
        /// </summary>
        internal static string _Custom_ {
            get {
                return ResourceManager.GetString("<Custom>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Join.
        /// </summary>
        internal static string _Join {
            get {
                return ResourceManager.GetString("&Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Split.
        /// </summary>
        internal static string _Split {
            get {
                return ResourceManager.GetString("&Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PDF Properties.
        /// </summary>
        internal static string Change_PDF_Properties {
            get {
                return ResourceManager.GetString("Change PDF Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing.
        /// </summary>
        internal static string Do_Nothing {
            get {
                return ResourceManager.GetString("Do Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails were successfully sent !.
        /// </summary>
        internal static string Emails_were_successfully_sent__ {
            get {
                return ResourceManager.GetString("Emails were successfully sent !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not run new Setup File !.
        /// </summary>
        internal static string Error__Could_not_run_new_Setup_File__ {
            get {
                return ResourceManager.GetString("Error. Could not run new Setup File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Setup File was not downloaded correctly !.
        /// </summary>
        internal static string Error__Setup_File_was_not_downloaded_correctly__ {
            get {
                return ResourceManager.GetString("Error. Setup File was not downloaded correctly !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not change Language !.
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not Decrypt File. Wrong Password ?.
        /// </summary>
        internal static string Error_could_not_Decrypt_File__Wrong_Password__ {
            get {
                return ResourceManager.GetString("Error could not Decrypt File. Wrong Password ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not encrypt File !.
        /// </summary>
        internal static string Error_could_not_encrypt_File__ {
            get {
                return ResourceManager.GetString("Error could not encrypt File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not parse Arguments !.
        /// </summary>
        internal static string Error_could_not_parse_Arguments__ {
            get {
                return ResourceManager.GetString("Error could not parse Arguments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not read File !.
        /// </summary>
        internal static string Error_could_not_read_File__ {
            get {
                return ResourceManager.GetString("Error could not read File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not read from Registry !.
        /// </summary>
        internal static string Error_could_not_read_from_Registry__ {
            get {
                return ResourceManager.GetString("Error could not read from Registry !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Could not set Update Proxy !.
        /// </summary>
        internal static string Error_Could_not_set_Update_Proxy__ {
            get {
                return ResourceManager.GetString("Error Could not set Update Proxy !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not write to Registry !.
        /// </summary>
        internal static string Error_could_not_write_to_Registry__ {
            get {
                return ResourceManager.GetString("Error could not write to Registry !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string Exit_Application {
            get {
                return ResourceManager.GetString("Exit Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Output File.
        /// </summary>
        internal static string Explore_Output_File {
            get {
                return ResourceManager.GetString("Explore Output File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist !.
        /// </summary>
        internal static string File_does_not_exist__ {
            get {
                return ResourceManager.GetString("File does not exist !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was Split Successfully !.
        /// </summary>
        internal static string File_was_Split_Successfully__ {
            get {
                return ResourceManager.GetString("File was Split Successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files were Joined Successfully !.
        /// </summary>
        internal static string Files_were_Joined_Successfully__ {
            get {
                return ResourceManager.GetString("Files were Joined Successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate.
        /// </summary>
        internal static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to upgrade to the latest version of the application. Press the OK button to download the new version.
        /// </summary>
        internal static string It_is_necessary_to_upgrade_to_the_latest_version_of_the_application__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("It is necessary to upgrade to the latest version of the application. Press the OK" +
                        " button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Files with Split Byte.
        /// </summary>
        internal static string Join_Files_with_Split_Byte {
            get {
                return ResourceManager.GetString("Join Files with Split Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Workstation.
        /// </summary>
        internal static string Lock_Workstation {
            get {
                return ResourceManager.GetString("Lock Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was Cancelled !.
        /// </summary>
        internal static string Operation_was_Cancelled__ {
            get {
                return ResourceManager.GetString("Operation was Cancelled !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUPTUT:.
        /// </summary>
        internal static string OUPTUT_ {
            get {
                return ResourceManager.GetString("OUPTUT:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_the_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out the Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid New File Path !.
        /// </summary>
        internal static string Please_insert_a_valid_New_File_Path__ {
            get {
                return ResourceManager.GetString("Please insert a valid New File Path !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert an Encryption Password !.
        /// </summary>
        internal static string Please_insert_an_Encryption_Password__ {
            get {
                return ResourceManager.GetString("Please insert an Encryption Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a desired file size of the split parts, or the number of parts the file should be splitted.\n.
        /// </summary>
        internal static string Please_specify_a_desired_file_size_of_the_split_parts__or_the_number_of_parts_the_file_should_be_splitted__n {
            get {
                return ResourceManager.GetString("Please specify a desired file size of the split parts, or the number of parts the" +
                        " file should be splitted.\\n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Join Output Filename !.
        /// </summary>
        internal static string Please_specify_a_Join_Output_Filename__ {
            get {
                return ResourceManager.GetString("Please specify a Join Output Filename !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Password !.
        /// </summary>
        internal static string Please_specify_a_Password__ {
            get {
                return ResourceManager.GetString("Please specify a Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Port Number !.
        /// </summary>
        internal static string Please_specify_a_Port_Number__ {
            get {
                return ResourceManager.GetString("Please specify a Port Number !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Recipient Email Address.
        /// </summary>
        internal static string Please_specify_a_Recipient_Email_Address {
            get {
                return ResourceManager.GetString("Please specify a Recipient Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a split parts output folder !.
        /// </summary>
        internal static string Please_specify_a_split_parts_output_folder__ {
            get {
                return ResourceManager.GetString("Please specify a split parts output folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Username !.
        /// </summary>
        internal static string Please_specify_a_Username__ {
            get {
                return ResourceManager.GetString("Please specify a Username !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Destination Folder !.
        /// </summary>
        internal static string Please_specify_a_valid_Destination_Folder__ {
            get {
                return ResourceManager.GetString("Please specify a valid Destination Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid File !.
        /// </summary>
        internal static string Please_specify_a_valid_File__ {
            get {
                return ResourceManager.GetString("Please specify a valid File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid File to Split !.
        /// </summary>
        internal static string Please_specify_a_valid_File_to_Split__ {
            get {
                return ResourceManager.GetString("Please specify a valid File to Split !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid First Split Part File !.
        /// </summary>
        internal static string Please_specify_a_valid_First_Split_Part_File__ {
            get {
                return ResourceManager.GetString("Please specify a valid First Split Part File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Output File !.
        /// </summary>
        internal static string Please_specify_a_valid_Output_File__ {
            get {
                return ResourceManager.GetString("Please specify a valid Output File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Server Port !.
        /// </summary>
        internal static string Please_specify_a_valid_Server_Port__ {
            get {
                return ResourceManager.GetString("Please specify a valid Server Port !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid split and join file !.
        /// </summary>
        internal static string Please_specify_a_valid_split_and_join_file__ {
            get {
                return ResourceManager.GetString("Please specify a valid split and join file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Split File Output Folder !.
        /// </summary>
        internal static string Please_specify_a_valid_Split_File_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify a valid Split File Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Split File Size !.
        /// </summary>
        internal static string Please_specify_a_valid_Split_File_Size__ {
            get {
                return ResourceManager.GetString("Please specify a valid Split File Size !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Split Input File !.
        /// </summary>
        internal static string Please_specify_a_valid_Split_Input_File__ {
            get {
                return ResourceManager.GetString("Please specify a valid Split Input File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Account Name !.
        /// </summary>
        internal static string Please_specify_an_Account_Name__ {
            get {
                return ResourceManager.GetString("Please specify an Account Name !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Email Account to use.
        /// </summary>
        internal static string Please_specify_an_Email_Account_to_use {
            get {
                return ResourceManager.GetString("Please specify an Email Account to use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Email Address !.
        /// </summary>
        internal static string Please_specify_an_Email_Address__ {
            get {
                return ResourceManager.GetString("Please specify an Email Address !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an existing File to Split !.
        /// </summary>
        internal static string Please_specify_an_existing_File_to_Split__ {
            get {
                return ResourceManager.GetString("Please specify an existing File to Split !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Interval in Seconds between Emails.
        /// </summary>
        internal static string Please_specify_an_Interval_in_Seconds_between_Emails {
            get {
                return ResourceManager.GetString("Please specify an Interval in Seconds between Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Outgoing Server !.
        /// </summary>
        internal static string Please_specify_an_Outgoing_Server__ {
            get {
                return ResourceManager.GetString("Please specify an Outgoing Server !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify Files to Join !.
        /// </summary>
        internal static string Please_specify_Files_to_Join__ {
            get {
                return ResourceManager.GetString("Please specify Files to Join !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify if the Split File Size will be Bytes, Mega Bytes e.t.c..
        /// </summary>
        internal static string Please_specify_if_the_Split_File_Size_will_be_Bytes__Mega_Bytes_e_t_c_ {
            get {
                return ResourceManager.GetString("Please specify if the Split File Size will be Bytes, Mega Bytes e.t.c.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify whether to split or join the file !.
        /// </summary>
        internal static string Please_specify_whether_to_split_or_join_the_file__ {
            get {
                return ResourceManager.GetString("Please specify whether to split or join the file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split File with Split Byte.
        /// </summary>
        internal static string Split_File_with_Split_Byte {
            get {
                return ResourceManager.GetString("Split File with Split Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission was cancelled !.
        /// </summary>
        internal static string Submission_was_cancelled__ {
            get {
                return ResourceManager.GetString("Submission was cancelled !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit and run the updated setup file.
        /// </summary>
        internal static string The_application_will_now_exit_and_run_the_updated_setup_file {
            get {
                return ResourceManager.GetString("The application will now exit and run the updated setup file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two Files have different MD5 Checksum Signatures !.
        /// </summary>
        internal static string The_two_Files_have_different_MD5_Checksum_Signatures__ {
            get {
                return ResourceManager.GetString("The two Files have different MD5 Checksum Signatures !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two Files have the same MD5 Checksum Signatures !.
        /// </summary>
        internal static string The_two_Files_have_the_same_MD5_Checksum_Signatures__ {
            get {
                return ResourceManager.GetString("The two Files have the same MD5 Checksum Signatures !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
    }
}
